(let ([h (hash '1 '2 '3 '4 '71 '1)])
  (+
   (guard (x [else '1])
          (hash-ref))
   (guard (x [else '1])
          (hash-ref h))
   (guard (x [else '1])
          (hash-ref h '1 '2 '3 '4))
   (guard (x [else 'BAD])
          (hash-ref h '71))
   (guard (x [else '1])
          (hash-ref h '2))
   (guard (x [else 'BAD])
          (hash-ref h '71 '12))
   (guard (x [else 'BAD])
          (hash-ref h '2 '1))
   (guard (_ [else '1])
          (apply hash-ref (list h)))
   (guard (_ [else '1])
          (apply hash-ref (list '0 '1 '2 '3 '4)))
   (guard (_ [else '1])
          (apply hash-ref (list h '2)))
   (apply hash-ref (list h '71))))
