(let ([v (vector '0 '1 '2)])
  (+
   (guard (_ [else '1])
          (vector-set!))
   (guard (_ [else '1])
          (vector-set! v '12 '1-billion-dollars!))
   (guard (_ [else 'BAD])
          (let ([unused (vector-set! v '2 '1)])
            (vector-ref v '2)))
   (guard (_ [else 'BAD])
          (let ([unused (apply vector-set! (list v '0 '1))])
            (vector-ref v '0)))
   (guard (_ [else '1])
          (apply vector-set! (list v '12 'BLURPLE-BEST_COLOR)))))
