((proc
  (main mainenv862487 mainargs862488)
  (let ((a '4))
    (let ((b '2))
      (let ((c (make-closure clo862485 b)))
        (let ((args862484$c$0 '())) (let ((args862484$c$1 (prim cons a args862484$c$0))) (clo-app c args862484$c$1)))))))
 (proc
  (clo862485 env862486 arglist862481)
  (let ((b (env-ref env862486 0)))
    (let ((d (prim car arglist862481)))
      (let ((e (prim + b d)))
        (let ((f (prim halt e))) (let ((args862483$f$0 '())) (let ((args862483$f$1 (prim cons f args862483$f$0))) (clo-app f args862483$f$1)))))))))
